services:

  app:
    image: monica:latest
    depends_on:
      - db
    ports:
      - "8200:80"
    environment:
      - APP_KEY=ChangeMeBy32KeyLengthOrGenerated
      - DB_HOST=db
      - DB_USERNAME=monica
      - DB_PASSWORD=secret      
    volumes:
      - ./data:/var/www/html/storage
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD=secret
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped






